<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12062" started-at="2021-08-05T02:25:08Z" finished-at="2021-08-05T02:25:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12062" started-at="2021-08-05T02:25:08Z" finished-at="2021-08-05T02:25:20Z">
      <class name="com.acti.testcase.LoginTest">
        <test-method status="PASS" signature="setUpReport()[pri:0, instance:com.acti.testcase.LoginTest@5e3a8624]" name="setUpReport" is-config="true" duration-ms="347" started-at="2021-08-05T07:55:08Z" finished-at="2021-08-05T07:55:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpReport -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.acti.testcase.LoginTest@5e3a8624]" name="setUp" is-config="true" duration-ms="7665" started-at="2021-08-05T07:55:08Z" finished-at="2021-08-05T07:55:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testLoginFunctionValidUser()[pri:0, instance:com.acti.testcase.LoginTest@5e3a8624]" name="testLoginFunctionValidUser" duration-ms="4006" started-at="2021-08-05T07:55:16Z" finished-at="2021-08-05T07:55:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Shantosh] but found [John Doe]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Shantosh] but found [John Doe]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.acti.testcase.LoginTest.testLoginFunctionValidUser(LoginTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginFunctionValidUser -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.acti.testcase.LoginTest@5e3a8624]" name="tearDown" is-config="true" duration-ms="368" started-at="2021-08-05T07:55:20Z" finished-at="2021-08-05T07:55:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLoginFunctionValidUser status=FAILURE method=LoginTest.testLoginFunctionValidUser()[pri:0, instance:com.acti.testcase.LoginTest@5e3a8624] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="flushReport()[pri:0, instance:com.acti.testcase.LoginTest@5e3a8624]" name="flushReport" is-config="true" duration-ms="516" started-at="2021-08-05T07:55:20Z" finished-at="2021-08-05T07:55:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReport -->
      </class> <!-- com.acti.testcase.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
